const $=s=>document.querySelector(s);const app=$('#app');
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;const pick=a=>a[Math.floor(Math.random()*a.length)];
let state=JSON.parse(localStorage.getItem('aflCareerSave')||'null');
let creator={name:'',position:'MID',height:188,weight:86,skin:'#b77851',hair:'#24160e',hairStyle:'Classic',number:7,points:32,attrs:{}};
function save(){localStorage.setItem('aflCareerSave',JSON.stringify(state))}function reset(){localStorage.removeItem('aflCareerSave');state=null;home()}
function shell(body){app.innerHTML=`<main class="shell"><div class="brand"><div class="brandmark"><span>AFC</span></div><div><div class="eyebrow">Unofficial football career simulator</div><h1>AFL Career</h1><div class="version">Version 0.1.0</div></div></div>${body}</main>`}
function home(){if(state)return hub();shell(`<section class="card hero"><div class="award">🏉</div><h2>Forge your football legacy</h2><p>Create an 18-year-old prospect, go No. 1 in a random draft and chase premierships and Brownlow glory across 25 seasons.</p><button onclick="character()">Start New Career</button><button class="secondary" onclick="about()">Game Guide</button></section><p class="notice">Real club and player names are used for this private, unofficial fan project. Original app icon and interface artwork.</p>`)}
function about(){shell(`<section class="card"><h2>Version 0.1</h2><p>This playable foundation includes character creation, a 70-overall build cap, random No. 1 draft, a two-year rookie contract, real clubs and a seeded real-player pool, four-quarter interactive matches, goal-kicking timing, earnings, purchases and Brownlow-style votes.</p><button onclick="home()">Back</button></section>`)}
function baseAttrs(pos){let o={};POSITIONS[pos].skills.forEach(s=>o[s]=62);return o}
function character(){creator.attrs=baseAttrs(creator.position);creator.points=32;renderCreator()}
function renderCreator(){let skills=POSITIONS[creator.position].skills;shell(`<section class="card"><div class="eyebrow">Step 1 of 2</div><h2>Create your player</h2><div class="avatar" style="--skin:${creator.skin};--hair:${creator.hair}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${creator.number}</div></div><div class="field"><label>Player name</label><input id="pname" value="${creator.name}" placeholder="Enter your name"></div><div class="grid3">${Object.entries(POSITIONS).map(([k,v])=>`<div class="option ${creator.position===k?'active':''}" onclick="setPos('${k}')"><b>${v.name}</b></div>`).join('')}</div><div class="grid2"><div class="field"><label>Height: ${creator.height} cm</label><input type="range" min="175" max="205" value="${creator.height}" oninput="creator.height=+this.value;renderCreator()"></div><div class="field"><label>Weight: ${creator.weight} kg</label><input type="range" min="70" max="115" value="${creator.weight}" oninput="creator.weight=+this.value;renderCreator()"></div><div class="field"><label>Skin tone</label><select onchange="creator.skin=this.value;renderCreator()"><option value="#f0c7a5">Light</option><option value="#d49a6a">Medium</option><option value="#b77851" selected>Tan</option><option value="#815235">Deep</option><option value="#4f2f20">Dark</option></select></div><div class="field"><label>Hair</label><select onchange="creator.hair=this.value;renderCreator()"><option value="#24160e">Dark brown</option><option value="#090909">Black</option><option value="#b87932">Blond</option><option value="#8e3b22">Auburn</option></select></div><div class="field"><label>Guernsey number</label><input type="number" min="1" max="99" value="${creator.number}" onchange="creator.number=+this.value"></div><div class="field"><label>Preferred foot</label><select id="foot"><option>Right</option><option>Left</option></select></div></div><button onclick="toAttributes()">Allocate Attributes</button><button class="ghost" onclick="home()">Cancel</button></section>`)}
function setPos(p){creator.name=$('#pname')?.value||creator.name;creator.position=p;creator.attrs=baseAttrs(p);creator.points=32;renderCreator()}
function toAttributes(){creator.name=$('#pname').value.trim()||'Rookie Star';attributeScreen()}
function overall(){let vals=Object.values(creator.attrs);return Math.round(vals.reduce((a,b)=>a+b,0)/vals.length)}
function attributeScreen(){shell(`<section class="card"><div class="eyebrow">Step 2 of 2</div><div class="topbar"><h2>Build your game</h2><span class="pill">${creator.points} points</span></div><p>Starting overall: <b>${overall()}</b>. No attribute can exceed 82 in creation.</p>${Object.entries(creator.attrs).map(([k,v])=>`<div class="statrow"><span>${k}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div><div class="grid2"><button class="secondary" onclick="changeAttr('${k}',-1)">−</button><button class="secondary" onclick="changeAttr('${k}',1)">+</button></div>`).join('')}<button class="gold" onclick="draft()" ${creator.points>0?'disabled':''}>Enter the Draft</button><button class="ghost" onclick="renderCreator()">Back</button></section>`)}
function changeAttr(k,d){if(d>0&&creator.points<=0)return;if(d>0&&creator.attrs[k]>=82)return;if(d<0&&creator.attrs[k]<=55)return;creator.attrs[k]+=d;creator.points-=d;attributeScreen()}
function draft(){let team=pick(TEAMS);state={version:'0.1.0',player:{...creator,age:18,overall:overall(),club:team.id,games:0,goals:0,votes:0,premierships:0,brownlows:0,careerEarnings:0,cash:0,fitness:100,form:70},season:1,round:1,contract:{years:2,salary:210000,matchPayment:5500},club:team.id,ladder:TEAMS.map(t=>({id:t.id,w:0,l:0,pf:0,pa:0})),history:[],assets:[],sponsors:[],brownlow:{},news:[]};save();shell(`<section class="card hero" style="border-color:${team.primary}"><div class="eyebrow">Pick No. 1</div><h2>${team.name}</h2><div class="avatar" style="--skin:${creator.skin};--hair:${creator.hair};--team:${team.primary}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${creator.number}</div></div><p>With the first selection in the national draft, <b>${team.name}</b> select <b>${creator.name}</b>, ${POSITIONS[creator.position].name.toLowerCase()}.</p><div class="card"><b>Two-year rookie deal</b><br>${money(state.contract.salary)} per season · ${money(state.contract.matchPayment)} per senior match</div><button onclick="hub()">Begin Career</button></section>`)}
function team(id){return TEAMS.find(t=>t.id===id)}
function nav(){return `<div class="nav"><button onclick="hub()">Home</button><button onclick="league()">League</button><button onclick="finance()">Money</button><button onclick="profile()">Player</button></div>`}
function hub(){let t=team(state.club),opp=TEAMS[(TEAMS.findIndex(x=>x.id===t.id)+state.round*5)%TEAMS.length];shell(`<section class="card" style="border-top:5px solid ${t.primary}"><div class="topbar"><div><div class="eyebrow">Season ${state.season} · Round ${state.round}</div><h2>${t.name}</h2></div><span class="pill">OVR ${state.player.overall}</span></div><div class="grid2"><div><small class="muted">Next opponent</small><h3>${opp.name}</h3></div><div><small class="muted">Current cash</small><h3>${money(state.player.cash)}</h3></div></div><button onclick="preview('${opp.id}')">Play Round ${state.round}</button></section><section class="grid2"><div class="card"><div class="eyebrow">Season</div><h2>${state.player.games}</h2><span class="muted">Games</span></div><div class="card"><div class="eyebrow">Brownlow</div><h2>${state.player.votes}</h2><span class="muted">Votes</span></div></section><section class="card"><h3>Career snapshot</h3><div class="listitem"><span>Goals</span><b>${state.player.goals}</b></div><div class="listitem"><span>Career earnings</span><b>${money(state.player.careerEarnings)}</b></div><div class="listitem"><span>Contract remaining</span><b>${state.contract.years} years</b></div></section>${nav()}`)}
function preview(oppId){let a=team(state.club),b=team(oppId);shell(`<section class="card hero"><div class="eyebrow">Round ${state.round}</div><h2>${a.name}<br><span class="muted">vs</span><br>${b.name}</h2><p>You are selected at ${POSITIONS[state.player.position].name}. Four compressed quarters; decisions appear whenever play reaches you.</p><button onclick="startMatch('${oppId}')">Centre Bounce</button><button class="ghost" onclick="hub()">Back</button></section>`)}
let match=null,timer=null,slider=null;
function startMatch(oppId){match={oppId,q:1,time:20,us:{g:0,b:0},them:{g:0,b:0},stats:{disp:0,k:0,h:0,m:0,t:0,g:0,b:0,impact:0},log:['The umpire sends the ball into the air.']};renderMatch();nextEvent()}
function score(x){return x.g*6+x.b}
function renderMatch(actions=''){let a=team(state.club),b=team(match.oppId);shell(`<div class="scoreboard"><div class="clock">Q${match.q} · ${String(match.time).padStart(2,'0')}:00</div><div class="teamscore"><div><b>${a.id}</b><div class="bigscore">${score(match.us)}</div><small>${match.us.g}.${match.us.b}</small></div><b>—</b><div><b>${b.id}</b><div class="bigscore">${score(match.them)}</div><small>${match.them.g}.${match.them.b}</small></div></div></div><section class="card event" id="event"><div class="eyebrow">Live play</div><h3>${match.log[match.log.length-1]}</h3>${actions}</section><section class="card"><div class="grid3"><div><b>${match.stats.disp}</b><br><small>Disposals</small></div><div><b>${match.stats.g}.${match.stats.b}</b><br><small>Goals</small></div><div><b>${match.stats.t}</b><br><small>Tackles</small></div></div><div class="ticker">${match.log.slice(-5).reverse().join('<br>')}</div></section>`)}
function nextEvent(){if(match.time<=0){if(match.q===4)return finishMatch();match.q++;match.time=20;match.log.push(`Quarter ${match.q} begins with another centre contest.`)}match.time-=rnd(1,4);if(match.time<0)match.time=0;let opponentScores=Math.random()<.48;if(opponentScores){Math.random()<.55?match.them.g++:match.them.b++;match.log.push(`${team(match.oppId).name} register a score.`)}let scenarios=state.player.position==='FWD'?['lead','ground','shot','pressure']:state.player.position==='DEF'?['intercept','spoil','rebound','tackle']:['clearance','receive','contest','tackle'];let s=pick(scenarios);let actions={lead:['Lead hard','Hold space','Double back'],ground:['Gather cleanly','Soccer forward','Tap to teammate'],shot:['Kick for goal','Centre the ball','Handball'],pressure:['Tackle','Corral','Smother'],intercept:['Attack the mark','Spoil','Stay goal-side'],spoil:['Punch boundary-side','Mark from behind','Body opponent'],rebound:['Short kick','Run and carry','Switch play'],tackle:['Tackle','Corral','Chase'],clearance:['Win clearance','Block teammate','Hold defensive side'],receive:['Kick long','Short pass','Handball'],contest:['Gather','Knock forward','Protect space']}[s];renderMatch(actions=`<div class="grid3">${actions.map(a=>`<button onclick="decision('${a.replaceAll("'","\\'")}')">${a}</button>`).join('')}</div>`)}
function decision(a){let skill=state.player.overall+(Math.random()*30-15);let success=skill>65;match.stats.impact+=success?rnd(5,10):rnd(-2,2);if(/Kick|pass|Centre|clearance|Gather|Run|rebound|Handball|Soccer/.test(a)){match.stats.disp++;if(/Handball/.test(a))match.stats.h++;else match.stats.k++}if(/Tackle|Corral|Chase/.test(a)&&success)match.stats.t++;if(/mark|Mark|Lead/.test(a)&&success)match.stats.m++;if(a==='Kick for goal')return goalSlider();match.log.push(success?`${state.player.name} executes: ${a}.`:`${a} breaks down under pressure.`);setTimeout(nextEvent,350)}
function goalSlider(){renderMatch(actions=`<p>Tap when the marker is in the green centre.</p><div class="sliderTrack"><div class="sliderMarker" id="marker"></div></div><button class="gold" onclick="stopKick()">KICK</button>`);let x=0,d=1;slider=setInterval(()=>{x+=d*3;if(x>=96||x<=0)d*=-1;let m=$('#marker');if(m)m.style.left=x+'%'},16);match.sliderX=()=>x}
function stopKick(){let x=match.sliderX();clearInterval(slider);let dist=Math.abs(50-x);let goal=dist<9+(state.player.attrs['Goal Kicking']||state.player.attrs['Disposal']||state.player.attrs['Rebound']||60)/18;if(goal){match.us.g++;match.stats.g++;match.stats.impact+=15;match.log.push(`${state.player.name} splits the middle!`)}else{match.us.b++;match.stats.b++;match.stats.impact+=3;match.log.push(`${state.player.name} misses for a behind.`)}setTimeout(nextEvent,450)}
function finishMatch(){let win=score(match.us)>=score(match.them);let a=state.ladder.find(x=>x.id===state.club),b=state.ladder.find(x=>x.id===match.oppId);a.pf+=score(match.us);a.pa+=score(match.them);b.pf+=score(match.them);b.pa+=score(match.us);win?(a.w++,b.l++):(a.l++,b.w++);let pay=state.contract.matchPayment;state.player.games++;state.player.goals+=match.stats.g;state.player.cash+=pay;state.player.careerEarnings+=pay;let votes=match.stats.impact>38?3:match.stats.impact>25?2:match.stats.impact>15?1:0;state.player.votes+=votes;state.brownlow[state.player.name]=(state.brownlow[state.player.name]||0)+votes;simulateVotes();state.history.push({season:state.season,round:state.round,opponent:match.oppId,result:win?'W':'L',score:`${score(match.us)}-${score(match.them)}`,stats:match.stats,votes});state.round++;if(state.round>23){state.season++;state.round=1;state.contract.years--;if(state.contract.years<=0)state.contract={years:pick([2,3,4,5]),salary:rnd(450,900)*1000,matchPayment:rnd(6,12)*1000}}save();shell(`<section class="card hero"><div class="award">${win?'🏆':'🏉'}</div><div class="eyebrow">Full time</div><h2>${win?'Victory':'Defeat'}</h2><p>${team(state.club).name} ${score(match.us)} — ${score(match.them)} ${team(match.oppId).name}</p><div class="grid3"><div><b>${match.stats.disp}</b><br><small>Disposals</small></div><div><b>${match.stats.g}.${match.stats.b}</b><br><small>Goals</small></div><div><b>${votes}</b><br><small>Votes</small></div></div><p>Match payment: <b>${money(pay)}</b></p><button onclick="hub()">Continue Career</button></section>`)}
function simulateVotes(){TEAMS.forEach(t=>{if(t.id===state.club)return;let p=pick(t.players);state.brownlow[p]=(state.brownlow[p]||0)+pick([0,0,0,1,2,3])})}
function league(){let standings=[...state.ladder].sort((a,b)=>b.w-a.w||(b.pf-b.pa)-(a.pf-a.pa));let votes=Object.entries(state.brownlow).sort((a,b)=>b[1]-a[1]).slice(0,10);shell(`<section class="card"><h2>Ladder</h2>${standings.map((x,i)=>`<div class="listitem"><span>${i+1}. <i class="teamdot" style="background:${team(x.id).primary}"></i>${team(x.id).name}</span><b>${x.w}-${x.l}</b></div>`).join('')}</section><section class="card"><h2>Brownlow Tracker</h2><p class="muted">Media estimate; official votes would normally remain secret.</p>${votes.length?votes.map((x,i)=>`<div class="listitem"><span>${i+1}. ${x[0]}</span><b>${x[1]}</b></div>`).join(''):'<p>No votes yet.</p>'}</section>${nav()}`)}
const SHOP=[['Starter apartment',380000],['Family home',850000],['Beach house',1800000],['Performance SUV',95000],['Luxury coupe',220000],['Home gym',28000],['Recovery suite',65000],['Designer watch',18000]];
function finance(){shell(`<section class="card"><div class="eyebrow">Available cash</div><h2>${money(state.player.cash)}</h2><div class="listitem"><span>Career earnings</span><b>${money(state.player.careerEarnings)}</b></div><div class="listitem"><span>Annual salary</span><b>${money(state.contract.salary)}</b></div><div class="listitem"><span>Match payment</span><b>${money(state.contract.matchPayment)}</b></div></section><section class="card"><h2>Lifestyle</h2>${SHOP.map(([n,p])=>`<div class="listitem"><span>${n}<br><small class="muted">${money(p)}</small></span><button style="width:auto" ${state.player.cash<p||state.assets.includes(n)?'disabled':''} onclick="buy('${n}',${p})">${state.assets.includes(n)?'Owned':'Buy'}</button></div>`).join('')}</section>${nav()}`)}
function buy(n,p){if(state.player.cash>=p){state.player.cash-=p;state.assets.push(n);save();finance()}}
function profile(){let t=team(state.club);shell(`<section class="card"><div class="avatar" style="--skin:${state.player.skin};--hair:${state.player.hair};--team:${t.primary}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${state.player.number}</div></div><h2 style="text-align:center">${state.player.name}</h2><p style="text-align:center" class="muted">${POSITIONS[state.player.position].name} · ${state.player.height} cm · ${state.player.weight} kg</p>${Object.entries(state.player.attrs).map(([k,v])=>`<div class="statrow"><span>${k}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('')}</section><section class="card"><button class="ghost" onclick="if(confirm('Delete this career permanently?'))reset()">Reset Career</button></section>${nav()}`)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');home();
