const $=s=>document.querySelector(s), app=$('#app');
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n||0);
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[Math.floor(Math.random()*a.length)], clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const SAVE_KEY='aflCareerSave';
const GAME_VERSION='0.4.0';
const PREF_KEY='aflCareerPrefs';
let prefs=JSON.parse(localStorage.getItem(PREF_KEY)||'null')||{sound:true,music:true,vibration:true};
function savePrefs(){localStorage.setItem(PREF_KEY,JSON.stringify(prefs))}
function tone(freq=440,duration=.08,type='sine',volume=.05){if(!prefs.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=volume;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.stop(ctx.currentTime+duration)}catch(e){}}
function buzz(pattern){if(prefs.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
let state=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');
let creator={name:'',position:'MID',height:188,weight:86,skin:'#b77851',hair:'#24160e',hairStyle:'Classic',number:7,foot:'Right',points:32,attrs:{}};
let match=null,slider=null;
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function restartCareer(){localStorage.removeItem(SAVE_KEY);state=null;creator={name:'',position:'MID',height:188,weight:86,skin:'#b77851',hair:'#24160e',hairStyle:'Classic',number:7,foot:'Right',points:32,attrs:{}};character()}
async function resetAllData(){localStorage.clear();sessionStorage.clear();if('caches' in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}location.reload()}
function reset(){restartCareer()}
function team(id){return TEAMS.find(t=>t.id===id)}
function roster(id){return REAL_PLAYERS.filter(p=>p.club===id)}
function playerByName(n){return REAL_PLAYERS.find(p=>p.name===n)}
function shell(body){app.innerHTML=`<main class="shell"><div class="brand"><div class="brandmark"><span>AFC</span></div><div><div class="eyebrow">Unofficial Australian football career simulator</div><h1>AFL Career</h1><div class="version">Version ${GAME_VERSION}</div></div></div>${body}</main>`}
function ensureState(){if(!state)return; if(state.version===GAME_VERSION)return;
 state.version=GAME_VERSION; state.phase=state.phase||'regular'; state.round=state.round||1; state.season=state.season||1;
 state.player.seasonGames=state.player.seasonGames||state.player.games||0; state.player.seasonGoals=state.player.seasonGoals||state.player.goals||0; state.player.seasonVotes=state.player.seasonVotes||state.player.votes||0;
 state.player.injury=null; state.player.suspension=0; state.player.form=state.player.form||70; state.player.fitness=state.player.fitness||100;
 state.schedule=makeFixture(state.season); state.currentFixture=0; state.stats=state.stats||{}; state.awards=state.awards||[]; state.records=state.records||{}; state.news=state.news||[];
 state.ladder=blankLadder(); state.brownlow=state.brownlow||{}; state.goals=state.goals||{}; save();}
function home(){ensureState();let career=state?`<section class="career-preview"><div><small>Current Career</small><strong>${state.player.name}</strong><span>${team(state.club).name} · Season ${state.season} · Round ${Math.min(state.round,23)}</span></div><div class="career-badge">${state.player.seasonVotes}<small>votes</small></div></section>`:'';shell(`<section class="card hero mainmenu"><div class="award football-spin">🏉</div><h2>Australian Football Career</h2><p>Build a 25-season football legacy and chase premierships, Brownlow Medals and career records.</p>${career}${state?`<button onclick="hub()">▶ Resume Career</button><button class="secondary" onclick="newCareerPrompt()">⭐ Start New Career</button>`:`<button onclick="character()">⭐ Start New Career</button>`}<button class="secondary" onclick="about()">Game Guide</button><button class="ghost" onclick="settings()">⚙ Settings</button><div class="menu-version">Version ${GAME_VERSION}</div></section><p class="notice">Real club and player names are included in this private, unofficial fan-made simulator.</p>`)}
function newCareerPrompt(){if(confirm('Start a new career? Your current career will be permanently overwritten.'))restartCareer()}
function restartCareerPrompt(){if(confirm('Restart your career? This will permanently delete the current career but keep the game installed.'))restartCareer()}
function settings(){shell(`<section class="card"><div class="eyebrow">Game settings</div><h2>Settings</h2><div class="toggle-row"><span>Sound effects</span><button class="toggle ${prefs.sound?'on':''}" onclick="prefs.sound=!prefs.sound;savePrefs();settings()">${prefs.sound?'On':'Off'}</button></div><div class="toggle-row"><span>Vibration</span><button class="toggle ${prefs.vibration?'on':''}" onclick="prefs.vibration=!prefs.vibration;savePrefs();settings()">${prefs.vibration?'On':'Off'}</button></div><div class="listitem"><span>Installed version</span><b>${GAME_VERSION}</b></div><button class="secondary" onclick="home()">Return to Main Menu</button></section><section class="card danger-card"><h3>Restart Career</h3><p>Deletes the current career and returns to character creation.</p><button class="danger" onclick="restartCareerPrompt()" ${state?'':'disabled'}>Restart Career</button></section><section class="card danger-card"><h3>Reset All Game Data</h3><p>Permanently clears saves, preferences, cached files and offline installation data.</p><button class="danger" onclick="if(confirm('Reset all AFL Career game data? This cannot be undone.'))resetAllData()">Reset All Game Data</button></section>`)}
function about(){shell(`<section class="card"><h2>What is new in v0.3</h2><p>Rebalanced live scoring, quarter-time, half-time and three-quarter-time score breaks, realistic team possession leaders, and a full-time summary showing the top ball winners from both clubs.</p><button onclick="home()">Back</button></section>`)}
function baseAttrs(pos){let o={};POSITIONS[pos].skills.forEach(s=>o[s]=62);return o}
function character(){creator.attrs=baseAttrs(creator.position);creator.points=32;renderCreator()}
function renderCreator(){shell(`<section class="card"><div class="eyebrow">Step 1 of 2</div><h2>Create your player</h2><div class="avatar" style="--skin:${creator.skin};--hair:${creator.hair}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${creator.number}</div></div><div class="field"><label>Player name</label><input id="pname" value="${creator.name}" placeholder="Enter your name"></div><div class="grid3">${Object.entries(POSITIONS).map(([k,v])=>`<div class="option ${creator.position===k?'active':''}" onclick="setPos('${k}')"><b>${v.name}</b></div>`).join('')}</div><div class="grid2"><div class="field"><label>Height: ${creator.height} cm</label><input type="range" min="175" max="205" value="${creator.height}" oninput="creator.height=+this.value;renderCreator()"></div><div class="field"><label>Weight: ${creator.weight} kg</label><input type="range" min="70" max="115" value="${creator.weight}" oninput="creator.weight=+this.value;renderCreator()"></div><div class="field"><label>Skin tone</label><select onchange="creator.skin=this.value;renderCreator()"><option value="#f0c7a5">Light</option><option value="#d49a6a">Medium</option><option value="#b77851">Tan</option><option value="#815235">Deep</option><option value="#4f2f20">Dark</option></select></div><div class="field"><label>Hair colour</label><select onchange="creator.hair=this.value;renderCreator()"><option value="#24160e">Dark brown</option><option value="#090909">Black</option><option value="#b87932">Blond</option><option value="#8e3b22">Auburn</option></select></div><div class="field"><label>Guernsey number</label><input type="number" min="1" max="99" value="${creator.number}" onchange="creator.number=clamp(+this.value,1,99)"></div><div class="field"><label>Preferred foot</label><select onchange="creator.foot=this.value"><option>Right</option><option>Left</option></select></div></div><button onclick="toAttributes()">Allocate Attributes</button><button class="ghost" onclick="home()">Cancel</button></section>`)}
function setPos(p){creator.name=$('#pname')?.value||creator.name;creator.position=p;creator.attrs=baseAttrs(p);creator.points=32;renderCreator()}
function toAttributes(){creator.name=$('#pname').value.trim()||'Rookie Star';attributeScreen()}
function overall(){let v=Object.values(creator.attrs);return Math.round(v.reduce((a,b)=>a+b,0)/v.length)}
function attributeScreen(){shell(`<section class="card"><div class="eyebrow">Step 2 of 2</div><div class="topbar"><h2>Build your game</h2><span class="pill">${creator.points} points</span></div><p>Starting overall: <b>${overall()}</b>. Creation maximum is 82.</p>${Object.entries(creator.attrs).map(([k,v])=>`<div class="statrow"><span>${k}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div><div class="grid2"><button class="secondary" onclick="changeAttr('${k}',-1)">−</button><button class="secondary" onclick="changeAttr('${k}',1)">+</button></div>`).join('')}<button class="gold" onclick="draft()" ${creator.points>0?'disabled':''}>Enter the Draft</button><button class="ghost" onclick="renderCreator()">Back</button></section>`)}
function changeAttr(k,d){if(d>0&&(creator.points<=0||creator.attrs[k]>=82))return;if(d<0&&creator.attrs[k]<=55)return;creator.attrs[k]+=d;creator.points-=d;attributeScreen()}
function blankLadder(){return TEAMS.map(t=>({id:t.id,p:0,w:0,l:0,d:0,pf:0,pa:0,pts:0}))}
function makeFixture(seed){let ids=TEAMS.map(t=>t.id), games=[]; for(let r=1;r<=23;r++){let rot=(r*5+seed*3)%ids.length; let order=ids.slice(rot).concat(ids.slice(0,rot)); if(r%2)order.reverse(); let pair=[]; for(let i=0;i<9;i++)pair.push({home:order[i],away:order[17-i]}); games.push(pair)} return games}
function draft(){let t=pick(TEAMS);state={version:GAME_VERSION,phase:'regular',season:1,round:1,currentFixture:0,player:{...creator,age:18,overall:overall(),club:t.id,games:0,goals:0,votes:0,seasonGames:0,seasonGoals:0,seasonVotes:0,premierships:0,brownlows:0,colemans:0,careerEarnings:0,cash:0,fitness:100,form:70,injury:null,suspension:0},club:t.id,contract:{years:2,salary:210000,matchPayment:5500},ladder:blankLadder(),schedule:makeFixture(1),history:[],assets:[],sponsors:[],brownlow:{},goals:{},awards:[],records:{},news:[`${creator.name} selected by ${t.name} with Pick No. 1.`],seasonSummary:null};save();shell(`<section class="card hero" style="border-color:${t.primary}"><div class="eyebrow">Pick No. 1</div><h2>${t.name}</h2><div class="avatar" style="--skin:${creator.skin};--hair:${creator.hair};--team:${t.primary}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${creator.number}</div></div><p>With the first selection, <b>${t.name}</b> select <b>${creator.name}</b>, ${POSITIONS[creator.position].name.toLowerCase()}.</p><div class="card"><b>Two-year contract</b><br>${money(state.contract.salary)} per season · ${money(state.contract.matchPayment)} per senior match</div><button onclick="hub()">Begin Career</button></section>`)}
function nav(){return `<div class="nav"><button onclick="home()">Menu</button><button onclick="hub()">Career</button><button onclick="league()">League</button><button onclick="finance()">Money</button><button onclick="profile()">Player</button></div>`}
function findUserFixture(){let round=state.schedule[state.round-1]||[];return round.find(g=>g.home===state.club||g.away===state.club)}
function ladderSorted(){return [...state.ladder].sort((a,b)=>b.pts-a.pts||percentage(b)-percentage(a)||b.pf-a.pf)}
function percentage(x){return x.pa?100*x.pf/x.pa:0}
function availability(){if(state.player.injury)return `Injured · ${state.player.injury.weeks} week${state.player.injury.weeks===1?'':'s'}`;if(state.player.suspension>0)return `Suspended · ${state.player.suspension} match${state.player.suspension===1?'':'es'}`;return 'Available'}
function hub(){ensureState();let t=team(state.club); if(state.phase==='seasonEnd')return seasonReview(); if(state.phase==='finals')return finalsHub(); let fx=findUserFixture(),opp=team(fx.home===state.club?fx.away:fx.home),rank=ladderSorted().findIndex(x=>x.id===state.club)+1;shell(`<section class="card" style="border-top:5px solid ${t.primary}"><div class="topbar"><div><div class="eyebrow">Season ${state.season} · Round ${state.round}</div><h2>${t.name}</h2></div><span class="pill">OVR ${state.player.overall}</span></div><div class="grid2"><div><small class="muted">Next opponent</small><h3>${opp.name}</h3></div><div><small class="muted">Ladder</small><h3>${rank}${['st','nd','rd'][rank-1]||'th'}</h3></div></div><div class="listitem"><span>Status</span><b>${availability()}</b></div><div class="listitem"><span>Fitness</span><b>${state.player.fitness}%</b></div><button onclick="preview('${opp.id}')">${availability()==='Available'?'Play':'Simulate'} Round ${state.round}</button></section><section class="grid2"><div class="card"><div class="eyebrow">Season games</div><h2>${state.player.seasonGames}</h2><span class="muted">Career ${state.player.games}</span></div><div class="card"><div class="eyebrow">Brownlow estimate</div><h2>${state.player.seasonVotes}</h2><span class="muted">votes</span></div></section><section class="card"><h3>Season snapshot</h3><div class="listitem"><span>Goals</span><b>${state.player.seasonGoals}</b></div><div class="listitem"><span>Form</span><b>${state.player.form}</b></div><div class="listitem"><span>Current cash</span><b>${money(state.player.cash)}</b></div><div class="listitem"><span>Contract remaining</span><b>${state.contract.years} years</b></div></section>${state.news.length?`<section class="card"><h3>Latest news</h3>${state.news.slice(-4).reverse().map(n=>`<p>${n}</p>`).join('')}</section>`:''}${nav()}`)}
function preview(oppId){let a=team(state.club),b=team(oppId),unavailable=availability()!=='Available';shell(`<section class="card hero"><div class="eyebrow">Season ${state.season} · Round ${state.round}</div><h2>${a.name}<br><span class="muted">vs</span><br>${b.name}</h2><p>${unavailable?`You are ${availability().toLowerCase()}. The match will be simulated.`:`Selected at ${POSITIONS[state.player.position].name}. Decisions appear whenever play reaches your player.`}</p><button onclick="${unavailable?`simulateUserAbsent('${oppId}')`:`startMatch('${oppId}')`}">${unavailable?'Simulate Match':'Centre Bounce'}</button><button class="ghost" onclick="hub()">Back</button></section>`)}
function seedMatchPlayers(clubId){let list=roster(clubId).slice().sort((a,b)=>b.ovr-a.ovr).slice(0,22);return list.map(p=>({name:p.name,club:clubId,pos:p.pos,ovr:p.ovr,disp:0,k:0,h:0,m:0,t:0,g:0,b:0}))}
function startMatch(oppId){let ours=seedMatchPlayers(state.club),theirs=seedMatchPlayers(oppId);ours.push({name:state.player.name,club:state.club,pos:state.player.position,ovr:state.player.overall,disp:0,k:0,h:0,m:0,t:0,g:0,b:0,created:true});match={oppId,q:1,time:20,us:{g:0,b:0},them:{g:0,b:0},stats:{disp:0,k:0,h:0,m:0,t:0,g:0,b:0,clr:0,int:0,impact:0},players:[...ours,...theirs],log:['The umpire sends the ball into the air.'],awaitingBreak:false};matchIntro()}
function matchIntro(){let a=team(state.club),b=team(match.oppId);tone(180,.16,'sawtooth',.04);shell(`<section class="broadcast-intro" style="--a:${a.primary};--b:${b.primary}"><div class="eyebrow">Season ${state.season} · Round ${state.round}</div><h2>FIRST QUARTER</h2><div class="versus"><strong>${a.name}</strong><span>VS</span><strong>${b.name}</strong></div><div class="centre-ball">🏉</div><h3>CENTRE BOUNCE</h3><button onclick="renderMatch();setTimeout(nextEvent,300)">Begin Match</button></section>`)}
function resultBanner(title,detail,type='success',icon='✓'){tone(type==='fail'?160:type==='goal'?620:440,type==='goal'?.22:.09,type==='fail'?'sawtooth':'sine',.06);buzz(type==='goal'?[100,50,180]:type==='fail'?[70,45,70]:[55]);let el=document.createElement('div');el.className=`result-overlay ${type}`;el.innerHTML=`<div class="result-icon">${icon}</div><div class="result-title">${title}</div><div class="result-detail">${detail||''}</div><div class="flying-ball">🏉</div>`;document.body.appendChild(el);setTimeout(()=>el.classList.add('show'),20);setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},850)}
function score(x){return x.g*6+x.b}
function topPossessions(limit=5){return [...match.players].sort((a,b)=>b.disp-a.disp||b.ovr-a.ovr).slice(0,limit)}
function renderMatch(actions=''){let a=team(state.club),b=team(match.oppId);shell(`<div class="scoreboard broadcast-score" style="--home:${a.primary};--away:${b.primary}"><div class="clock">Q${match.q} · ${String(match.time).padStart(2,'0')}:00</div><div class="teamscore"><div class="score-team home"><b>${a.id}</b><div class="bigscore">${score(match.us)}</div><small>${match.us.g}.${match.us.b}</small></div><div class="live-ball">🏉</div><div class="score-team away"><b>${b.id}</b><div class="bigscore">${score(match.them)}</div><small>${match.them.g}.${match.them.b}</small></div></div></div><section class="oval-stage"><div class="oval-lines"></div><div class="ball-sprite">🏉</div><div class="event-copy"><div class="eyebrow">Live play</div><h3>${match.log.at(-1)}</h3></div></section><section class="card action-panel">${actions||'<div class="waiting">Play developing…</div>'}</section><section class="player-stat-cards"><div><b>${match.stats.disp}</b><span>Disposals</span></div><div><b>${match.stats.g}.${match.stats.b}</b><span>Score</span></div><div><b>${match.stats.t}</b><span>Tackles</span></div></section><section class="card ticker-card"><div class="ticker">${match.log.slice(-5).reverse().join('<br>')}</div></section>`)}
function simulatePassage(){let ours=team(state.club),opp=team(match.oppId),homeEdge=(ours.strength+state.player.overall*.12+state.player.form*.05)-(opp.strength);let usChance=clamp(.50+homeEdge*.009,.35,.66);let attackingUs=Math.random()<usChance;let side=attackingUs?match.us:match.them;let clubId=attackingUs?state.club:match.oppId;let pool=match.players.filter(p=>p.club===clubId&&!p.created);let touches=rnd(2,5);for(let i=0;i<touches;i++){let p=pick(pool);if(!p)continue;p.disp++;Math.random()<.57?p.k++:p.h++;if(Math.random()<.20)p.m++;if(Math.random()<.11)p.t++}let scoringChance=.34;if(Math.random()<scoringChance){let goalChance=clamp(.53+(attackingUs?homeEdge:-homeEdge)*.006,.40,.68);if(Math.random()<goalChance)side.g++;else side.b++;let scorer=pick(pool.filter(p=>p.pos==='FWD').length?pool.filter(p=>p.pos==='FWD'):pool);if(scorer){if(Math.random()<goalChance)scorer.g++;else scorer.b++}}}
function quarterBreak(){let labels={1:'QUARTER TIME',2:'HALF TIME',3:'THREE-QUARTER TIME'};let leaders=topPossessions(5),a=team(state.club),b=team(match.oppId),margin=Math.abs(score(match.us)-score(match.them)),lead=score(match.us)===score(match.them)?'Scores level':`${score(match.us)>score(match.them)?a.name:b.name} lead by ${margin}`;tone(260,.25,'square',.045);buzz([90,80,90]);shell(`<section class="break-screen" style="--home:${a.primary};--away:${b.primary}"><div class="eyebrow">${labels[match.q]}</div><div class="break-score"><div><strong>${a.name}</strong><b>${match.us.g}.${match.us.b} (${score(match.us)})</b></div><div><strong>${b.name}</strong><b>${match.them.g}.${match.them.b} (${score(match.them)})</b></div></div><h3>${lead}</h3></section><section class="card"><h3>⭐ Top Performers</h3>${leaders.map((p,i)=>`<div class="performer"><span><b>${i+1}. ${p.name}</b><small>${team(p.club).name} · ${p.g} goal${p.g===1?'':'s'}</small></span><strong>${p.disp}</strong></div>`).join('')}<button onclick="resumeQuarter()">Begin Quarter ${match.q+1}</button></section>`)}
function resumeQuarter(){match.q++;match.time=20;match.awaitingBreak=false;match.log.push(`Quarter ${match.q} begins.`);tone(320,.12,'square',.04);renderMatch();resultBanner(`QUARTER ${match.q}`,'The ball is back in play','neutral','🏉');setTimeout(nextEvent,950)}
function nextEvent(){if(match.time<=0){if(match.q===4)return finishMatch();match.awaitingBreak=true;return quarterBreak()}let elapsed=rnd(1,3);match.time=Math.max(0,match.time-elapsed);for(let i=0;i<elapsed;i++)simulatePassage();let situations={MID:[['The ball spills from the stoppage.',['Win clearance','Quick handball','Kick forward','Tackle']]],FWD:[['The ball enters the forward 50.',['Lead and mark','Gather at ground level','Apply pressure','Kick for goal']]],DEF:[['The opposition attacks.',['Intercept mark','Spoil','Tackle','Rebound kick']]]};let s=pick(situations[state.player.position]);renderMatch(s[1].map(a=>`<button class="${a.includes('goal')?'gold':'secondary'}" onclick="decision('${a.replaceAll("'","\\'")}')">${a}</button>`).join(''))}
function skillFor(action){let a=state.player.attrs;if(action.includes('goal'))return a['Goal Kicking']||a.Disposal||a.Rebound;if(action.includes('mark'))return a.Marking||a.Intercept||a.Strength;if(action.includes('Tackle')||action.includes('pressure'))return a.Tackling;if(action.includes('clearance'))return a.Clearance;if(action.includes('handball'))return a.Disposal||a.Composure;if(action.includes('Spoil'))return a.Spoiling;return a.Disposal||a.Rebound||a.Composure}
function decision(action){if(action.includes('goal'))return kickSlider();let skill=skillFor(action),success=Math.random()*100<skill*.72+state.player.form*.15-state.player.fitness*.02;if(success){match.stats.impact+=rnd(4,9);let cp=match.players.find(p=>p.created);if(cp){if(action.includes('Tackle')||action.includes('pressure'))match.stats.t++;else if(action.includes('mark'))match.stats.m++;else{match.stats.disp++;action.includes('handball')?match.stats.h++:match.stats.k++}if(action.includes('clearance'))match.stats.clr++;if(action.includes('Intercept'))match.stats.int++;cp.disp=match.stats.disp;cp.k=match.stats.k;cp.h=match.stats.h;cp.m=match.stats.m;cp.t=match.stats.t}if(Math.random()<.16){Math.random()<.62?match.us.g++:match.us.b++}let labels=action.includes('Tackle')?'HOLDING THE BALL!':action.includes('mark')?'MARK TAKEN!':action.includes('handball')?'PERFECT HANDBALL':action.includes('clearance')?'CLEARANCE WON!':action.includes('Spoil')?'GREAT SPOIL!':action.includes('Intercept')?'INTERCEPT MARK!':'LASER PASS!';match.log.push(`${state.player.name} executes: ${action}.`);resultBanner(labels,action,'success','✓')}else{match.stats.impact-=1;match.log.push(`${state.player.name} is beaten attempting to ${action.toLowerCase()}.`);resultBanner('TURNOVER!',`Failed: ${action}`,'fail','✕')}renderMatch();setTimeout(nextEvent,950)}
function kickSlider(){renderMatch(`<div class="kickbar"><div class="target"></div><div class="sliderMarker" id="marker"></div></div><button class="gold" onclick="stopKick()">KICK</button>`);let x=0,d=1;slider=setInterval(()=>{x+=d*3;if(x>=96||x<=0)d*=-1;let m=$('#marker');if(m)m.style.left=x+'%'},16);match.sliderX=()=>x}
function stopKick(){let x=match.sliderX();clearInterval(slider);let skill=skillFor('goal'),dist=Math.abs(50-x),goal=dist<7+skill/16;if(goal){match.us.g++;match.stats.g++;let cp=match.players.find(p=>p.created);if(cp){cp.g++;cp.disp++;cp.k++;}match.stats.impact+=15;match.log.push(`${state.player.name} kicks truly!`);resultBanner('GOAL!!','Six points · Crowd erupts','goal','🏉')}else{match.us.b++;match.stats.b++;let cp=match.players.find(p=>p.created);if(cp){cp.b++;cp.disp++;cp.k++;}match.stats.impact+=3;match.log.push(`${state.player.name} misses for a behind.`);resultBanner('BEHIND','One point','neutral','•')}renderMatch();setTimeout(nextEvent,1050)}
function simScore(strength){let g=clamp(Math.round(rnd(6,15)+(strength-75)*.22),3,22),b=rnd(5,14);return {g,b}}
function applyResult(home,away,hs,as){let h=state.ladder.find(x=>x.id===home),a=state.ladder.find(x=>x.id===away);h.p++;a.p++;h.pf+=score(hs);h.pa+=score(as);a.pf+=score(as);a.pa+=score(hs);if(score(hs)>score(as)){h.w++;h.pts+=4;a.l++}else if(score(as)>score(hs)){a.w++;a.pts+=4;h.l++}else{h.d++;a.d++;h.pts+=2;a.pts+=2}}
function simulateOtherGames(userFx,userUs,userThem){let round=state.schedule[state.round-1];round.forEach(g=>{if(g===userFx){applyResult(g.home,g.away,g.home===state.club?userUs:userThem,g.home===state.club?userThem:userUs);return}let h=simScore(team(g.home).strength+rnd(-3,3)),a=simScore(team(g.away).strength+rnd(-3,3));applyResult(g.home,g.away,h,a);generatePlayerStats(g.home,h.g);generatePlayerStats(g.away,a.g);awardSimVotes(g.home,g.away)})}
function generatePlayerStats(club,goals){let list=roster(club);for(let i=0;i<goals;i++){let pool=list.filter(p=>p.pos==='FWD');let p=pick(pool.length?pool:list);state.goals[p.name]=(state.goals[p.name]||0)+1}}
function awardSimVotes(a,b){let pool=[...roster(a),...roster(b)].sort(()=>Math.random()-.5).sort((x,y)=>(y.ovr+rnd(-10,10))-(x.ovr+rnd(-10,10))).slice(0,3);[3,2,1].forEach((v,i)=>state.brownlow[pool[i].name]=(state.brownlow[pool[i].name]||0)+v)}
function progressRound(){state.player.fitness=clamp(state.player.fitness+rnd(8,15),35,100);if(state.player.injury){state.player.injury.weeks--;if(state.player.injury.weeks<=0){state.news.push(`${state.player.name} has recovered from ${state.player.injury.name}.`);state.player.injury=null}}if(state.player.suspension>0)state.player.suspension--; state.round++;if(state.round>23){state.phase='finals';prepareFinals()}save()}
function maybeInjury(){if(Math.random()<.055){let injuries=[['Hamstring strain',rnd(2,5)],['Ankle sprain',rnd(1,4)],['Shoulder injury',rnd(2,6)],['Concussion',1],['Calf strain',rnd(1,3)]];let i=pick(injuries);state.player.injury={name:i[0],weeks:i[1]};state.news.push(`${state.player.name} suffered a ${i[0]} and will miss approximately ${i[1]} week${i[1]===1?'':'s'}.`)}}
function finishMatch(){let fx=findUserFixture(),win=score(match.us)>score(match.them),pay=state.contract.matchPayment;state.player.games++;state.player.seasonGames++;state.player.goals+=match.stats.g;state.player.seasonGoals+=match.stats.g;state.goals[state.player.name]=(state.goals[state.player.name]||0)+match.stats.g;state.player.cash+=pay;state.player.careerEarnings+=pay;state.player.fitness=clamp(state.player.fitness-rnd(10,20),20,100);state.player.form=clamp(Math.round(state.player.form*.75+(50+match.stats.impact)*.25),35,95);let votes=match.stats.impact>44?3:match.stats.impact>29?2:match.stats.impact>17?1:0;state.player.votes+=votes;state.player.seasonVotes+=votes;state.brownlow[state.player.name]=(state.brownlow[state.player.name]||0)+votes;state.history.push({season:state.season,round:state.round,opponent:match.oppId,result:win?'W':'L',score:`${score(match.us)}-${score(match.them)}`,stats:match.stats,votes});simulateOtherGames(fx,match.us,match.them);maybeInjury();progressRound();save();let leaders=topPossessions(8);shell(`<section class="final-screen ${win?'win':'loss'}" style="--home:${team(state.club).primary};--away:${team(match.oppId).primary}"><div class="award">${win?'🏆':'🏉'}</div><div class="eyebrow">FINAL SCORE</div><h2>${win?'VICTORY':'DEFEAT'}</h2><div class="break-score"><div><strong>${team(state.club).name}</strong><b>${match.us.g}.${match.us.b} (${score(match.us)})</b></div><div><strong>${team(match.oppId).name}</strong><b>${match.them.g}.${match.them.b} (${score(match.them)})</b></div></div></section><section class="player-stat-cards final-stats"><div><b>${match.stats.disp}</b><span>Disposals</span></div><div><b>${match.stats.g}.${match.stats.b}</b><span>Goals</span></div><div><b>${votes}</b><span>Votes</span></div></section><section class="card"><h3>⭐ Top Performers</h3>${leaders.map((p,i)=>`<div class="performer"><span><b>${i+1}. ${p.name}</b><small>${team(p.club).name} · ${p.g} goal${p.g===1?'':'s'}</small></span><strong>${p.disp}</strong></div>`).join('')}<div class="listitem"><span>Match payment</span><b>${money(pay)}</b></div><button onclick="hub()">Continue Career</button></section>`);tone(win?620:180,.28,win?'sine':'sawtooth',.055);buzz(win?[120,70,200]:[120])}function simulateUserAbsent(oppId){let fx=findUserFixture(),us=simScore(team(state.club).strength),them=simScore(team(oppId).strength);simulateOtherGames(fx,us,them);progressRound();shell(`<section class="card hero"><div class="eyebrow">Full time</div><h2>${score(us)>score(them)?'Club victory':'Club defeat'}</h2><p>${team(state.club).name} ${score(us)} — ${score(them)} ${team(oppId).name}</p><p>You did not play because you were ${availability().toLowerCase()}.</p><button onclick="hub()">Continue</button></section>`)}
function prepareFinals(){let top=ladderSorted().slice(0,8).map(x=>x.id);state.finals={week:1,alive:[...top],top,results:[],champion:null};state.news.push(`The home-and-away season is complete. ${team(top[0]).name} finished on top.`)}
function finalsHub(){let f=state.finals;if(f.champion){state.phase='seasonEnd';save();return seasonReview()}let inFinals=f.alive.includes(state.club);shell(`<section class="card hero"><div class="eyebrow">Finals · Week ${f.week}</div><h2>${inFinals?'Your premiership campaign continues':'Finals series'}</h2><p>${inFinals?'Win to keep your season alive.':'Your club has been eliminated. Simulate the remaining finals to discover the premier.'}</p><button onclick="playFinalsWeek()">${inFinals?'Play Finals Week':'Simulate Finals Week'}</button></section><section class="card"><h3>Teams remaining</h3>${f.alive.map(id=>`<div class="listitem"><span>${team(id).name}</span><b>${team(id).strength}</b></div>`).join('')}</section>${nav()}`)}
function playFinalsWeek(){let f=state.finals,ordered=f.alive.sort((a,b)=>f.top.indexOf(a)-f.top.indexOf(b)),next=[];for(let i=0;i<ordered.length;i+=2){let a=ordered[i],b=ordered[i+1];if(!b){next.push(a);continue}let as=team(a).strength+rnd(-8,8),bs=team(b).strength+rnd(-8,8);if(a===state.club)as+=state.player.overall/10;if(b===state.club)bs+=state.player.overall/10;let winner=as>=bs?a:b;next.push(winner);f.results.push({week:f.week,a,b,winner})}f.alive=next;f.week++;if(next.length===1){f.champion=next[0];if(f.champion===state.club){state.player.premierships++;state.player.cash+=100000;state.player.careerEarnings+=100000;state.news.push(`${state.player.name} is a premiership player!`)}state.phase='seasonEnd'}save();hub()}
function seasonReview(){if(!state.seasonSummary){let votes=Object.entries(state.brownlow).sort((a,b)=>b[1]-a[1]),goals=Object.entries(state.goals).sort((a,b)=>b[1]-a[1]),brown=votes[0]||['No winner',0],cole=goals[0]||['No winner',0];if(brown[0]===state.player.name){state.player.brownlows++;state.player.cash+=75000;state.player.careerEarnings+=75000}if(cole[0]===state.player.name)state.player.colemans++;state.seasonSummary={premier:state.finals?.champion||ladderSorted()[0].id,brownlow:brown,coleman:cole};save()}let s=state.seasonSummary;shell(`<section class="card hero"><div class="award">🏆</div><div class="eyebrow">Season ${state.season} complete</div><h2>${team(s.premier).name} Premiers</h2><p><b>Brownlow:</b> ${s.brownlow[0]} (${s.brownlow[1]} votes)<br><b>Leading goalkicker:</b> ${s.coleman[0]} (${s.coleman[1]} goals)</p><div class="grid3"><div><b>${state.player.seasonGames}</b><br><small>Games</small></div><div><b>${state.player.seasonGoals}</b><br><small>Goals</small></div><div><b>${state.player.seasonVotes}</b><br><small>Votes</small></div></div><button onclick="newSeason()">Begin Next Season</button></section>${nav()}`)}
function newSeason(){state.player.cash+=state.contract.salary;state.player.careerEarnings+=state.contract.salary;state.contract.years--;if(state.contract.years<=0){state.contract={years:pick([2,3,4,5]),salary:rnd(450,950)*1000,matchPayment:rnd(6,12)*1000};state.news.push(`${state.player.name} signed a new ${state.contract.years}-year contract worth ${money(state.contract.salary)} per season.`)}state.season++;state.round=1;state.phase='regular';state.schedule=makeFixture(state.season);state.ladder=blankLadder();state.brownlow={};state.goals={};state.finals=null;state.seasonSummary=null;state.player.age++;state.player.seasonGames=0;state.player.seasonGoals=0;state.player.seasonVotes=0;state.player.fitness=100;state.player.form=70;if(state.player.age<=25&&Math.random()<.75){let k=pick(Object.keys(state.player.attrs));state.player.attrs[k]=clamp(state.player.attrs[k]+1,40,96);state.player.overall=Math.round(Object.values(state.player.attrs).reduce((a,b)=>a+b,0)/Object.values(state.player.attrs).length)}if(state.season>25){return retirement()}save();hub()}
function retirement(){shell(`<section class="card hero"><div class="award">🏅</div><h2>Career Complete</h2><p>${state.player.name} retires after 25 seasons.</p><div class="listitem"><span>Games</span><b>${state.player.games}</b></div><div class="listitem"><span>Goals</span><b>${state.player.goals}</b></div><div class="listitem"><span>Brownlows</span><b>${state.player.brownlows}</b></div><div class="listitem"><span>Premierships</span><b>${state.player.premierships}</b></div><div class="listitem"><span>Career earnings</span><b>${money(state.player.careerEarnings)}</b></div><button class="ghost" onclick="restartCareerPrompt()">New Career</button></section>`)}
function league(){let standings=ladderSorted(),votes=Object.entries(state.brownlow).sort((a,b)=>b[1]-a[1]).slice(0,10),goals=Object.entries(state.goals).sort((a,b)=>b[1]-a[1]).slice(0,10);shell(`<section class="card"><h2>Ladder</h2>${standings.map((x,i)=>`<div class="listitem"><span>${i+1}. <i class="teamdot" style="background:${team(x.id).primary}"></i>${team(x.id).name}</span><b>${x.pts} · ${percentage(x).toFixed(1)}%</b></div>`).join('')}</section><section class="card"><h2>Brownlow Tracker</h2>${votes.length?votes.map((x,i)=>`<div class="listitem"><span>${i+1}. ${x[0]}</span><b>${x[1]}</b></div>`).join(''):'<p>No votes yet.</p>'}</section><section class="card"><h2>Leading Goalkickers</h2>${goals.length?goals.map((x,i)=>`<div class="listitem"><span>${i+1}. ${x[0]}</span><b>${x[1]}</b></div>`).join(''):'<p>No goals yet.</p>'}</section>${nav()}`)}
const SHOP=[['Starter apartment',380000],['Family home',850000],['Beach house',1800000],['Performance SUV',95000],['Luxury coupe',220000],['Home gym',28000],['Recovery suite',65000],['Designer watch',18000]];
function finance(){shell(`<section class="card"><div class="eyebrow">Available cash</div><h2>${money(state.player.cash)}</h2><div class="listitem"><span>Career earnings</span><b>${money(state.player.careerEarnings)}</b></div><div class="listitem"><span>Annual salary</span><b>${money(state.contract.salary)}</b></div><div class="listitem"><span>Match payment</span><b>${money(state.contract.matchPayment)}</b></div></section><section class="card"><h2>Lifestyle</h2>${SHOP.map(([n,p])=>`<div class="listitem"><span>${n}<br><small class="muted">${money(p)}</small></span><button style="width:auto" ${state.player.cash<p||state.assets.includes(n)?'disabled':''} onclick="buy('${n}',${p})">${state.assets.includes(n)?'Owned':'Buy'}</button></div>`).join('')}</section>${nav()}`)}
function buy(n,p){if(state.player.cash>=p){state.player.cash-=p;state.assets.push(n);save();finance()}}
function profile(){let t=team(state.club);shell(`<section class="card"><div class="avatar" style="--skin:${state.player.skin};--hair:${state.player.hair};--team:${t.primary}"><div class="head"></div><div class="hair"></div><div class="body"></div><div class="shorts"></div><div class="num">${state.player.number}</div></div><h2 style="text-align:center">${state.player.name}</h2><p style="text-align:center" class="muted">${POSITIONS[state.player.position].name} · ${state.player.height} cm · ${state.player.weight} kg · Age ${state.player.age}</p>${Object.entries(state.player.attrs).map(([k,v])=>`<div class="statrow"><span>${k}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('')}</section><section class="card"><h3>Career honours</h3><div class="listitem"><span>Premierships</span><b>${state.player.premierships}</b></div><div class="listitem"><span>Brownlows</span><b>${state.player.brownlows}</b></div><div class="listitem"><span>Leading goalkicker awards</span><b>${state.player.colemans}</b></div><button class="ghost" onclick="restartCareerPrompt()">Restart Career</button><button class="secondary" onclick="settings()">Settings</button></section>${nav()}`)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.addEventListener('pageshow',()=>home());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!match)home()});home();
